chore: update max python version
MeltanoLabs/tap-duckdb pull request #7
Opened 2024-01-30 14:35 UTC by riccelso

2024-01-30 16:02 UTC, visch commented
Could you extend our CI tests to include the latest version of Python (we can remove Python 3.7)

https://github.com/MeltanoLabs/tap-duckdb/blob/main/.github/workflows/ci_workflow.yml#L38

`python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]`

I can't modify your fork so I thought this would be easiest.

Thanks

2024-01-30 16:02 UTC, visch requested changes

2024-01-30 16:02 UTC, visch commented on pyproject.toml
> +python = "<3.12,>=3.7.1"
Thank you for putting in this PR. 

Since we're here could we just support up to Python 3.12 so 
```suggestion
python = "<3.13,>=3.7.1"
```

2024-02-12 20:16 UTC, riccelso commented
Apologies for the delay

2024-03-27 19:11 UTC, merged